// Local-only safety checks. No real recipients or provider calls.
import { chromium } from 'playwright';
import { createHmac, randomUUID } from 'node:crypto';
import { execFileSync } from 'node:child_process';
import { transform } from 'esbuild';
import fs from 'node:fs';
import assert from 'node:assert/strict';
const base='http://localhost:3000',hid=900061,other=900062;
const token=id=>{const p=`${id}.${Date.now()+3600000}`;return p+'.'+createHmac('sha256','pc-dev-session-secret').update(p).digest('base64url')};
const sql=q=>execFileSync('npx',['wrangler','d1','execute','patient-connect-production','--local','--persist-to','.wrangler/category-tests','--command',q],{stdio:'pipe'});
const clean=()=>sql(`DELETE FROM views WHERE dispatch_id IN (SELECT id FROM dispatches WHERE hospital_id IN (${hid},${other})); DELETE FROM dispatches WHERE hospital_id IN (${hid},${other}); DELETE FROM scoped_annotations WHERE hospital_id IN (${hid},${other}); DELETE FROM material_annotations WHERE hospital_id IN (${hid},${other}); DELETE FROM material_sets WHERE hospital_id IN (${hid},${other}); DELETE FROM materials WHERE hospital_id IN (${hid},${other}); DELETE FROM hospitals WHERE id IN (${hid},${other});`);
async function api(path,body,method=body===undefined?'GET':'POST',id=hid,headers={}){const r=await fetch(base+'/api'+path,{method,headers:{Cookie:'pc_session='+token(id),'Content-Type':'application/json',...headers},body:body===undefined?undefined:JSON.stringify(body)});return {status:r.status,data:await r.json()}}
async function prepare(b){const p=await api('/dispatches/preview',b);assert.equal(p.status,200,p.data.error);return {...b,preview_hash:p.data.preview_hash,request_key:randomUUID(),confirmed:true}}
let checks=0;const check=(v,l)=>{assert(v,l);checks++;console.log('PASS',l)};
const count=async()=> (await api('/dispatches')).data.dispatches.length;
const bytes=fs.readFileSync('public/static/mockups/implant.png'), png='data:image/png;base64,'+bytes.toString('base64');
const stroke={tool:'pen',color:'#ee5555',width:6,points:[[.1,.1],[.3,.3]]};
const browser=await chromium.launch();clean();sql(`INSERT INTO hospitals(id,ps_hospital_id,name) VALUES (${hid},'safety-qa','안전 검증 치과'),(${other},'safety-other','다른 치과');`);
try {
  await api('/materials/examples',{confirmed:true});const materials=(await api('/materials')).data.materials,first=materials[0];
  const cost=(await api('/materials',{kind:'cost',title:'공용 비용',cost:[{name:'검증',price:10000}]})).data.material;
  const before=(await api('/materials',{kind:'before_after',title:'합성 사례'})).data.material;
  check((await api('/dispatches/preview',{channel:'link',material_ids:[before.id]})).status===400,'Unreviewed before-after is blocked from external sharing');
  check((await api('/dispatches/preview',{channel:'link',material_ids:[cost.id]})).status===400,'Cost guide requires scope dates and uncertainty terms');
  const g={included:'검진 및 안내',extra:'없음',alternatives:'대안은 진단 후',basis_date:new Date().toISOString().slice(0,10),valid_until:'2099-12-31',variability:'검사 후 치료 범위가 달라질 수 있습니다.'};
  await api('/materials/'+cost.id,{...cost,guidance:{...g,valid_until:'2020-01-01'}},'PUT');
  check((await api('/dispatches/preview',{channel:'link',material_ids:[cost.id]})).status===400,'Expired cost guidance is blocked');
  await api('/materials/'+cost.id,{...cost,guidance:{...g,basis_date:'2026-02-30'}},'PUT');
  check((await api('/dispatches/preview',{channel:'link',material_ids:[cost.id]})).status===400,'Impossible calendar dates are rejected');
  await api('/materials/'+cost.id,{...cost,guidance:g},'PUT');
  const caseG={external_allowed:true,deidentified:true,consent_ref:'QA-DOC: 안내장 전송 허용',treatment:'합성 치료 안내',period:'테스트 기간',individual_notice:'치료 결과에는 개인차가 있습니다.'};
  sql(`UPDATE materials SET images_json='[{"key":"examples/implant.png"},{"key":"examples/orthodontics.png"}]' WHERE id=${before.id}`);
  await api('/materials/'+before.id,{...before,guidance:caseG},'PUT');
  const approved=await api('/dispatches/preview',{channel:'link',material_ids:[before.id,cost.id]});
  check(approved.status===200,'Reviewed case and current cost guide can be previewed');
  check(!JSON.stringify(approved.data).includes('QA-DOC'),'Private consent reference is not in patient snapshot');
  check((await api('/settings',{phone:'041-123-1234',chat_url:'javascript:alert(1)'},'PUT')).status===400,'Unsafe contact protocols are rejected');
  check((await api('/settings',{chat_url:'https://evil.invalid'},'PUT')).status===400,'Kakao contact is restricted to official channel URLs');
  await api('/settings',{phone:'041-123-1234',chat_url:'https://pf.kakao.com/_test/chat',booking_url:'https://example.com/booking',link_days:30},'PUT');
  check((await api('/me')).data.hospital.booking_url==='https://example.com/booking','Clinic contact settings persist');
  check((await api('/material-sets',{name:'임플란트 안내',material_ids:[first.id,cost.id]})).status===200,'Clinic can save ordered reusable set');
  await api('/material-sets',{name:'임플란트 안내',material_ids:[cost.id,first.id]});
  const sets=(await api('/material-sets')).data.sets;
  check(sets.length===1&&sets[0].material_ids[0]===cost.id,'Same named set updates without duplicate and preserves order');
  check((await api('/material-sets',undefined,'GET',other)).data.sets.length===0,'Sets are clinic isolated');
  check((await api('/material-sets',{name:'forbidden',material_ids:[first.id]},'POST',other)).status===400,'Other clinic cannot store foreign material references');
  check((await api('/material-sets',{name:'cross',material_ids:[first.id]},'POST',hid,{Origin:'https://other.invalid'})).status===403,'Cross-origin mutations are rejected');
  const path=`/materials/${first.id}/annotations`,payload={media_key:first.images[0].key,strokes:[stroke],image_png:png,version:0,write_key:randomUUID()};
  await api(path,payload,'PUT');
  const scope=(await api('/annotation-sessions',{})).data.scope;
  const copy=(await api('/annotation-sessions',{copy_shared:true,material_ids:[first.id]})).data.scope;
  check((await api(path+'?scope='+scope)).data.annotations.length===0,'Fresh explanation starts without previous shared marks');
  check((await api(path+'?scope='+copy)).data.annotations.length===1,'Shared notes are copied only after explicit choice');
  await api(path+'?scope='+scope,payload,'PUT');
  check((await api(path+'?scope='+scope,undefined,'GET',other)).status===404,'Scope knowledge cannot bypass clinic ownership');
  check((await api(path+'?scope=invalid')).status===400,'Malformed annotation scope is rejected');
  await api(path+'?scope='+scope,{...payload,strokes:[],image_png:null,version:1,write_key:randomUUID()},'PUT');
  check((await api(path)).data.annotations[0].strokes.length===1&&(await api(path+'?scope='+copy)).data.annotations[0].strokes.length===1,'Clearing a consultation does not change originals or another consultation');
  const withNotes=await api('/dispatches/preview',{channel:'link',material_ids:[first.id],include_annotations:true,annotation_scope:copy});
  const noNotes=await api('/dispatches/preview',{channel:'link',material_ids:[first.id],include_annotations:true,annotation_scope:scope});
  check(withNotes.data.materials[0].annotations.length===1&&noNotes.data.materials[0].annotations.length===0,'Preview resolves notes only from selected consultation');
  const basePayload={channel:'link',material_ids:[first.id,before.id,cost.id],include_annotations:true,annotation_scope:copy};
  const n=await count();let prepared=await prepare(basePayload);
  check(await count()===n,'Preview creates no dispatch or patient view');
  check((await api('/dispatches',{...prepared,confirmed:false})).status===409,'Final acknowledgement is mandatory');
  check((await api('/dispatches',{...prepared,preview_hash:'invalid'})).status===409,'Wrong preview digest is rejected');
  await api('/materials/'+first.id,{...first,title:'Updated after preview'},'PUT');
  check((await api('/dispatches',prepared)).status===409,'Material changed after preview cannot be silently sent');
  prepared=await prepare(basePayload);
  const results=await Promise.all([api('/dispatches',prepared),api('/dispatches',prepared)]);
  check(results.every(r=>r.status===200)&&results[0].data.id===results[1].data.id,'Concurrent retries produce a single dispatch');
  check(await count()===n+1,'Exactly one dispatch is persisted');
  const published=results[0].data;
  check((await api('/dispatches',{...prepared,label:'changed'})).status===409,'Same idempotency key cannot change payload');
  const replay=await api('/dispatches',prepared);check(replay.data.replayed&&replay.data.id===published.id,'Lost-response request replays original result');
  const patient=(await api('/g/'+published.token)).data;
  check(patient.hospital.chat_url.includes('pf.kakao.com')&&patient.materials[2].guidance.included===g.included,'Patient guide has contact links and cost terms');
  check(!JSON.stringify(patient).includes('QA-DOC'),'Consent record stays private after actual publication');
  check((await api('/dispatches/'+published.id+'/status',{},'POST',other)).status===404,'Dispatch status query checks ownership');
  // Upload invalidates previous external media approval.
  await api('/materials/'+before.id+'/images?key=examples%2Forthodontics.png',undefined,'DELETE');
  check((await api('/materials')).data.materials.find(m=>m.id===before.id).guidance.external_allowed===false,'Changing case media revokes external sharing approval');
  check((await api('/dispatches/preview',{channel:'link',material_ids:[before.id]})).status===400,'Changed case cannot be sent without renewed review');
  check((await api('/g/'+published.token)).data.materials[1].images.length===2,'Existing published snapshots survive later case changes');
  // Browser flow: new/continue, reusable set, preflight, confirmation, ambiguous response replay.
  const ctx=await browser.newContext({viewport:{width:1280,height:960}});await ctx.addCookies([{name:'pc_session',value:token(hid),url:base}]);
  const p=await ctx.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('dialog',d=>d.accept());
  await p.goto(base+'/app');await p.waitForSelector('#browse-all');await p.locator('#browse-all').click();await p.waitForSelector('[data-preview]');await p.locator(`[data-preview="${first.id}"]`).click();
  check(await p.locator('#session-clean').isVisible(),'Starting an explanation requires an explicit clean or saved choice');
  await p.locator('#session-copy').click();await p.waitForSelector('[data-tool="pen"]:enabled');
  check(await p.evaluate(()=>PCAnnotations.hasMarks([Number(document.querySelector('[data-preview]').dataset.preview)])),'Explicitly copied shared strokes render in explanation');
  const oldScope=await p.evaluate(()=>sessionStorage.getItem('pc_scope_900061'));await p.locator('#cl').click();
  await p.locator(`[data-preview="${first.id}"]`).click();await p.locator('#session-clean').click();await p.waitForSelector('[data-tool="pen"]:enabled');
  check(!await p.evaluate(()=>PCAnnotations.hasMarks([Number(document.querySelector('[data-preview]').dataset.preview)])),'New clean explanation shows no previous annotations');
  check(await p.evaluate(()=>sessionStorage.getItem('pc_scope_900061'))!==oldScope,'New explanation gets an independent persisted scope');
  await p.locator('#ex').click();await p.waitForSelector('#s-link');check(!await p.locator('#s-annotations').isChecked(),'Sending defaults to original materials only');
  await p.locator('[data-tab="library"]').click();await p.locator('.library-bundles>summary').click();await p.locator('[data-set]').click();await p.locator('[data-tab="send"]').click();await p.locator('#send-order').click();
  const uiCount=await count();await p.locator('#s-link').click();await p.waitForSelector('#dispatch-preview');
  check((await p.locator('.preview-content').innerText()).includes('공용 비용 안내'),'Final preview uses patient renderer with cost terms');
  check(await p.locator('.preview-content a[href="https://example.com/booking"]').count()===1,'Preview includes configured booking button');
  check(await count()===uiCount,'Opening the UI preview sends nothing');
  await p.locator('#preview-send').click();check((await p.locator('#preview-error').innerText()).includes('체크'),'Final checkbox prevents accidental publication');
  await p.locator('#preview-confirmed').check();
  let lost=false;await p.route('**/api/dispatches',async route=>{if(route.request().method()==='POST'&&!lost){lost=true;await route.fetch();await route.abort('failed')}else await route.continue()});
  await p.locator('#preview-send').click();await p.waitForFunction(()=>document.querySelector('#preview-send')?.textContent.includes('다시 확인'));
  check(await p.locator('#preview-cancel').isDisabled(),'Ambiguous send result locks new attempts until same-key reconciliation');
  await p.unroute('**/api/dispatches');await p.locator('#preview-send').click();await p.waitForSelector('#dispatch-preview',{state:'detached'});
  check(await count()===uiCount+1,'UI lost-response retry does not duplicate a dispatch');
  await p.locator('[data-tab="settings"]').click();check(await p.locator('#st-chat').inputValue()==='https://pf.kakao.com/_test/chat','Contact settings restore in editor');
  await p.locator('[data-tab="library"]').click();await p.locator(`[data-edit="${cost.id}"]`).click();check(await p.locator('[data-guidance="included"]').inputValue()===g.included,'Cost fields restore in material editor');await p.locator('#ed-close').click();
  await p.setViewportSize({width:390,height:844});await p.locator('[data-tab="send"]').click();await p.locator('#s-link').click();await p.waitForSelector('#dispatch-preview');
  check(await p.locator('#dispatch-preview').evaluate(e=>e.getBoundingClientRect().right<=innerWidth),'Final preview fits mobile');
  await p.screenshot({path:'.test-results/safety-preview-mobile.png'});await p.locator('#preview-cancel').click();
  const guest=await browser.newPage({viewport:{width:390,height:844}});guest.on('pageerror',e=>errors.push(e.message));await guest.goto(base+'/g/'+published.token);await guest.waitForSelector('[data-i]');
  check(await guest.locator('a[href="https://example.com/booking"]').count()===1,'Patient has a working booking destination');
  check(await guest.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Patient cost and case guidance fits mobile');
  check(errors.length===0,'No uncaught browser errors in safety workflows');
  // Provider behavior uses a stubbed Fetch, never sends traffic to SOLAPI.
  const code=(await transform(fs.readFileSync('src/lib/solapi.ts','utf8'),{loader:'ts',format:'esm'})).code;
  const provider=await import('data:text/javascript;base64,'+Buffer.from(code).toString('base64'));
  const realFetch=globalThis.fetch,env={SOLAPI_API_KEY:'fixture',SOLAPI_API_SECRET:'fixture',PLATFORM_PF_ID:'fixture',CONNECT_TEMPLATE_ID:'fixture'};
  try {
    globalThis.fetch=async()=>new Response(JSON.stringify({groupInfo:{groupId:'fixture-group'}}),{status:200});check((await provider.sendAlimtalk(env,'01000000000',{})).ok,'Provider request acknowledgement is accepted, not delivery confirmation');
    globalThis.fetch=async()=>{throw new Error('lost')};check((await provider.sendAlimtalk(env,'01000000000',{})).uncertain,'Network ambiguity is not reported as definite failure');
    globalThis.fetch=async()=>new Response('{}',{status:503});check((await provider.sendAlimtalk(env,'01000000000',{})).uncertain,'Provider server errors are treated as uncertain');
    globalThis.fetch=async()=>new Response('{}',{status:200});check((await provider.sendAlimtalk(env,'01000000000',{})).uncertain,'Missing receipt ID is not a success claim');
    globalThis.fetch=async()=>new Response(JSON.stringify({count:{sentSuccess:1,sentFailed:0}}));check((await provider.deliveryStatus(env,'fixture-group')).status==='delivered','Explicit delivery count confirms delivery');
    globalThis.fetch=async()=>new Response(JSON.stringify({count:{sentSuccess:0,sentFailed:1}}));check((await provider.deliveryStatus(env,'fixture-group')).status==='failed','Explicit delivery failure is distinguishable from pending');
    globalThis.fetch=async()=>new Response(JSON.stringify({count:{sentSuccess:0,sentFailed:0}}));check((await provider.deliveryStatus(env,'fixture-group')).status==='accepted','Pending receipt stays accepted');
  } finally {globalThis.fetch=realFetch}
  fs.writeFileSync('.test-results/consultation-safety-results.json',JSON.stringify({checks,errors,real_messages_sent:0},null,2));console.log(`${checks} safety checks passed`);
} finally {await browser.close();clean()}
