// Local-only dental taxonomy and example import tests; never calls messaging providers.
import { chromium } from 'playwright';
import { createHmac } from 'node:crypto';
import { execFileSync } from 'node:child_process';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const base = 'http://localhost:3000';
const ids = [900011, 900012];
const sql = command => execFileSync('npx', ['wrangler','d1','execute','patient-connect-production','--local','--persist-to','.wrangler/category-tests','--command',command], {stdio:'pipe'});
const token = id => { const p=`${id}.${Date.now()+3600000}`; return p+'.'+createHmac('sha256','pc-dev-session-secret').update(p).digest('base64url'); };
async function api(path, body, id=ids[0], method=body===undefined?'GET':'POST', headers={}) {
 const r=await fetch(base+'/api'+path,{method,headers:{...(id?{Cookie:'pc_session='+token(id)}:{}),'Content-Type':'application/json',...headers},body:body===undefined?undefined:JSON.stringify(body)});
 return {status:r.status,data:await r.json()};
}
let count=0; const check=(ok,label)=>{assert(ok,label);count++;console.log('PASS',label);};
const clean = () => sql('DELETE FROM views WHERE dispatch_id IN (SELECT id FROM dispatches WHERE hospital_id IN (900011,900012)); DELETE FROM dispatches WHERE hospital_id IN (900011,900012); DELETE FROM materials WHERE hospital_id IN (900011,900012); DELETE FROM hospitals WHERE id IN (900011,900012);');
clean();
sql("INSERT INTO hospitals (id,ps_hospital_id,name) VALUES (900011,'library-qa','예시 검증 치과'),(900012,'library-qa-ui','예시 화면 치과');");
const browser=await chromium.launch();
try {
 const meta=(await api('/material-library')).data;
 check(meta.categories.explain.includes('치아교정')&&meta.categories.explain.includes('보철치료'),'Treatment categories include ordinary dental specialties');
 check(meta.categories.disease.includes('치수·치근단 질환')&&!meta.categories.disease.includes('임플란트'),'Disease categories are distinct from treatment procedures');
 check(meta.examples.length===8&&meta.imported_count===0,'Eight example outlines are available without importing on read');
 check((await api('/materials')).data.materials.length===0,'Viewing catalog does not modify library');
 check((await api('/materials/examples',{confirmed:true},null)).status===401,'Example import requires authentication');
 check((await api('/materials/examples',{})).status===400,'Example import requires explicit acknowledgement');
 check((await api('/materials/examples',{confirmed:true},ids[0],'POST',{Origin:'https://other.invalid'})).status===403,'Cross-origin example insertion is rejected');
 const own=await api('/materials',{kind:'explain',category:'병원 맞춤 분류',title:'기존 병원 자료',body:'변경하면 안 되는 원문'});
 const imported=await Promise.all([api('/materials/examples',{confirmed:true,hospital_id:ids[1]}),api('/materials/examples',{confirmed:true})]);
 check(imported.every(r=>r.status===200)&&imported.reduce((n,r)=>n+r.data.added,0)===8,'Concurrent repeated imports add eight records exactly once');
 let materials=(await api('/materials')).data.materials;
 check(materials.length===9&&materials.find(m=>m.id===own.data.material.id).body==='변경하면 안 되는 원문','Examples preserve pre-existing hospital records');
 check((await api('/materials',undefined,ids[1])).data.materials.length===0,'Client-supplied hospital ID cannot insert into another clinic');
 const examples=materials.filter(m=>m.is_example), first=examples[0];
 check(examples.length===8&&examples.every(m=>m.body.includes('검토용 예시')&&m.images.length===0&&m.cost.length===0),'All examples are labeled drafts with no fabricated photos or fees');
 check(examples.filter(m=>m.kind==='explain').length===4&&examples.filter(m=>m.kind==='disease').length===4,'Example pack covers four treatments and four diseases');
 await api('/materials/'+first.id,{...first,title:'병원에서 수정한 예시'},ids[0],'PUT');
 await api('/materials/'+examples[1].id,undefined,ids[0],'DELETE');
 const retry=await api('/materials/examples',{confirmed:true});
 materials=(await api('/materials')).data.materials;
 check(retry.data.added===0&&materials.find(m=>m.id===first.id).title==='병원에서 수정한 예시','Retry does not overwrite edited examples');
 check(!materials.some(m=>m.id===examples[1].id),'Retry does not resurrect deleted examples');
 const ctx=await browser.newContext({viewport:{width:1360,height:1000}});
 await ctx.addCookies([{name:'pc_session',value:token(ids[1]),url:base}]);
 const p=await ctx.newPage(), errors=[];p.on('pageerror',e=>errors.push(e.message));
 await p.goto(base+'/app');await p.waitForSelector('#add-examples');
 await p.locator('[data-kind-filter="explain"]').click();
 check(await p.locator('[data-cat="임플란트"]').count()===1&&await p.locator('[data-cat="보철치료"]').count()===1,'Preset treatment filters are visible even with no materials');
 await p.locator('[data-cat="임플란트"]').click();await p.locator('[data-kind-filter="disease"]').click();
 check(await p.locator('[data-cat="충치"]').count()===1&&await p.locator('[data-cat="임플란트"]').count()===0,'Switching kind replaces presets and clears stale procedure filter');
 check(await p.locator('[data-cat=""]').getAttribute('aria-pressed')==='true','Kind switch resets subcategory selection');
 await p.locator('#add-examples').click();await p.waitForSelector('#sample-import');
 check(await p.locator('#example-dialog li').count()===8,'Example dialog lists all eight templates before insertion');
 await p.locator('#sample-import').click();
 check((await p.locator('#sample-status').innerText()).includes('먼저 확인'),'UI prevents unconfirmed import');
 await p.locator('#sample-confirm').check();await p.locator('#sample-import').click();await p.waitForSelector('#example-dialog',{state:'detached'});
 check(await p.locator('[data-add]').count()===8,'Confirming example import populates the material library');
 check(await p.locator('#add-examples').isDisabled(),'UI records completed import and prevents duplicate clicks');
 await p.reload();await p.waitForSelector('[data-kind-filter]');
 check(await p.locator('[data-add]').count()===8,'Imported material library persists after reload');
 await p.locator('[data-kind-filter="explain"]').click();await p.locator('[data-cat="보철치료"]').click();
 check(await p.locator('[data-add]').count()===1,'Treatment subtype filters its matching example');
 await p.locator('#new').click();
 check(await p.locator('#ed-category-select').inputValue()==='보철치료','Registration defaults to selected dental subtype');
 await p.locator('[data-kind="disease"]').click();
 check(await p.locator('#ed-category-select option[value="충치"]').count()===1&&await p.locator('#ed-category-select option[value="임플란트"]').count()===0,'Editor subtype options follow the selected material kind');
 check(await p.locator('#ed-cat').inputValue()==='보철치료','Switching editor kind preserves prior category as custom instead of silently deleting');
 await p.locator('#ed-category-select').selectOption('충치');await p.locator('#ed-title').fill('직접 작성한 충치 자료');await p.locator('#ed-save').click();await p.waitForSelector('#ed-del');await p.locator('#ed-close').click();
 check((await api('/materials',undefined,ids[1])).data.materials.some(m=>m.title==='직접 작성한 충치 자료'&&m.kind==='disease'&&m.category==='충치'&&!m.is_example),'Dropdown-selected subtype persists without forged example provenance');
 await p.locator('[data-kind-filter="disease"]').click();await p.locator('[data-cat="치아균열·파절"]').click();await p.locator('[data-add]').click();await p.locator('[data-tab="send"]').click();
 check((await p.locator('#main').innerText()).includes('검토용 예시가 포함'),'Sending view warns before sharing example content');
 const pack=(await api('/materials',undefined,ids[1])).data.materials.filter(m=>m.is_example);
 const published=(await api('/dispatches',{channel:'link',material_ids:[pack[0].id]},ids[1])).data;
 const patient=await browser.newPage();await patient.goto(base+'/g/'+published.token);await patient.waitForSelector('[data-i]');
 check((await patient.locator('#app').innerText()).includes('검토용 예시자료입니다'),'Patient guide retains explicit example provenance');
 await p.locator('[data-tab="library"]').click();await p.locator('[data-kind-filter="explain"]').click();
 fs.mkdirSync('.test-results',{recursive:true});await p.waitForTimeout(3000);await p.screenshot({path:'.test-results/dental-treatment-examples.png',fullPage:true});
 await p.locator('[data-kind-filter="disease"]').click();await p.waitForTimeout(350);await p.screenshot({path:'.test-results/dental-disease-examples.png',fullPage:true});
 await p.setViewportSize({width:390,height:844});
 check(await p.locator('.material-category-filters').evaluate(el=>el.getBoundingClientRect().right<=innerWidth),'Dental subtype filters fit mobile');
 await p.locator('#new').click();
 check(await p.locator('#ed-category-select').evaluate(el=>el.getBoundingClientRect().right<=innerWidth),'Mobile registration subtype selector stays within viewport');
 await p.locator('#ed-close').click();await p.waitForTimeout(350);await p.screenshot({path:'.test-results/dental-examples-mobile.png',fullPage:true});
 check(errors.length===0,'No uncaught errors in taxonomy and sample workflows');
 fs.writeFileSync('.test-results/material-library-results.json',JSON.stringify({checks:count,errors},null,2));
 console.log(`${count} dental library checks passed`);
} finally { await browser.close(); clean(); }
